version: '3'
services:
  server:
    build: .
    command: pm2-dev index.js
    environment:
      NODE_ENV: development
      NODE_APP_INSTANCE: ''
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules

  nginx:
    image: nginx:1.13.11
    links:
      - server
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:3.6.3
    command: mongod
    ports:
      - "27017:27017"
